#!/bin/bash
# Configure RetroArch for Raspberry Pi 4B with 2GB RAM
# Optimized settings for memory-constrained systems

set -e

CONFIG_DIR="$HOME/.config/retroarch"
CONFIG_FILE="$CONFIG_DIR/retroarch.cfg"

echo "Configuring RetroArch for Pi 4B 2GB RAM..."

# Create config directory if it doesn't exist
mkdir -p "$CONFIG_DIR"

# Backup existing config if it exists
if [ -f "$CONFIG_FILE" ]; then
    BACKUP_FILE="${CONFIG_FILE}.bak.$(date +%Y%m%d%H%M%S)"
    cp "$CONFIG_FILE" "$BACKUP_FILE"
    echo "Backed up existing config to: $BACKUP_FILE"
fi

# Create optimized RetroArch config
cat > "$CONFIG_FILE" <<'EOF'
# RetroArch config optimized for Raspberry Pi 4B 2GB RAM
# Generated by Magic Dingus Box setup script

# Video settings (memory-conscious, 1080p)
video_driver = "gl"
video_fullscreen = true
video_fullscreen_x = "1920"
video_fullscreen_y = "1080"
video_windowed_fullscreen = false
video_smooth = false
video_threaded = true
video_hard_sync = false
video_vsync = true
video_max_swapchain_images = 2
video_gpu_record = false
video_record = false
video_shader_enable = false
video_filter = ""
video_scale_integer = false

# Audio settings - ensure audio is enabled and not muted
audio_driver = "alsa"
audio_device = "alsa/hdmi:CARD=vc4hdmi0,DEV=0"
audio_enable = "true"
audio_mute_enable = "false"
audio_volume = "1.0"
audio_latency = 64
audio_resampler = "sinc"
audio_out_rate = "48000"
audio_sync = "true"

# Performance optimizations
savefile_compression = false
savestate_compression = false

# Input settings - Controller autodetection and configuration
input_joypad_driver = "udev"
input_autodetect_enable = "true"
input_auto_game_focus = "true"
input_menu_toggle_gamepad_combo = "0"
input_enable_hotkey = true
input_hotkey_block_delay = 0
input_toggle_fullscreen = "f"
input_menu_toggle = "f1"
input_reset = "r"
input_exit_emulator = "escape"
input_menu_ok = "nul"
input_menu_cancel = "nul"
input_menu_up = "nul"
input_menu_down = "nul"
input_menu_left = "nul"
input_menu_right = "nul"
input_overlay_enable = false
# Controller deadzone and sensitivity
input_analog_deadzone = "0.15"
input_analog_sensitivity = "1.0"
input_axis_threshold = "0.5"

# Memory management (defaults are usually fine, but documented here)
# cache_directory = ""
# savefile_directory = ""
# savestate_directory = ""
EOF

# Set proper permissions
chmod 644 "$CONFIG_FILE"
echo "✓ Created optimized RetroArch config at: $CONFIG_FILE"

# Verify config file
if [ -f "$CONFIG_FILE" ]; then
    echo "✓ Config file verified"
    echo ""
    echo "Configuration complete!"
    echo "Config file location: $CONFIG_FILE"
    echo ""
    echo "Key optimizations for 2GB RAM:"
    echo "  - Video driver: OpenGL ES (hardware-accelerated)"
    echo "  - Swapchain images: 2 (reduced from default 3)"
    echo "  - Shaders disabled (saves memory/CPU)"
    echo "  - Recording disabled (saves memory/CPU)"
    echo "  - Filters disabled (saves memory/CPU)"
    echo "  - Compression disabled (faster, less CPU)"
    echo "  - HDMI audio device configured"
else
    echo "ERROR: Failed to create config file!"
    exit 1
fi

